### ISSUE TITLE
File opening errors in logger

### ISSUE THREAD

**Issue by slava-semeniuk-ek** [amplitude/Amplitude-Swift#175]
I'm currently tracking errors from Amplitude to our error analytics, and I've encountered a significant number of errors in our production app. All the errors are similar in nature, and here are a couple of examples:

- The file “v2-80” couldn’t be opened because there is no such file.
- “v2-13” couldn’t be removed.

I'm concerned about whether these errors could potentially cause any data issues?

SDK Version: 1.6.0
OS Info: iOS 17.*

**Comment by crleona** [comment]
Hi @slava-semeniuk-ek - Could you please double check the version of Amplitude-Swift you are using? 1.6.0 was just released two days ago. Any stack traces you can provide would also be very helpful.

**Comment by slava-semeniuk-ek** [comment]
For the latest version which uses 1.6.0, I could find the following errors:

**NSLocalizedDescription: “v2-8” couldn’t be removed.**
<details>
<summary>Logs</summary>

AmplitudeErrorLogger.swift - Line 41
specialized AmplitudeMessageLogger.record(issue:message:) + 41

AmplitudeErrorLogger.swift - Line 24
protocol witness for Logger.error(message:) in conformance AmplitudeMessageLogger + 24

PersistentStorage.swift - Line 104
closure #1 in PersistentStorage.remove(eventBlock:) + 104

<compiler-generated>
partial apply for thunk for @callee_guaranteed () -> ()

libdispatch.dylib
_dispatch_sync_f_slow

PersistentStorage.swift - Line 100
PersistentStorage.remove(eventBlock:) + 100

<compiler-generated>
protocol witness for Storage.remove(eventBlock:) in conformance PersistentStorage

IdentifyInterceptor.swift - Line 124
IdentifyInterceptor.getCombinedInterceptedIdentify() + 124

IdentifyInterceptor.swift - Line 157
implicit closure #2 in implicit closure #1 in closure #1 in IdentifyInterceptor.scheduleTransferInterceptedIdentifyEvent() + 157

IdentifyInterceptor.swift - Line 182
closure #1 in IdentifyInterceptor.scheduleTransferInterceptedIdentifyEvent() + 182

QueueTimer.swift - Line 38
closure #1 in QueueTimer.init(interval:once:queue:handler:) + 38
</details>

**The file “v2-243” couldn’t be opened using text encoding Unicode (UTF-8).**
<details>
<summary>Logs</summary>
AmplitudeErrorLogger.swift - Line 24

protocol witness for Logger.error(message:) in conformance AmplitudeMessageLogger + 24

PersistentStorage.swift - Line 94
PersistentStorage.getEventsString(eventBlock:) + 94

<compiler-generated>
protocol witness for Storage.getEventsString(eventBlock:) in conformance PersistentStorage

EventPipeline.swift - Line 70
closure #1 in EventPipeline.flush(completion:) + 70

<compiler-generated>
thunk for @callee_guaranteed () -> ()

_dispatch_lane_barrier_sync_invoke_and_complete

EventPipeline.swift - Line 65
EventPipeline.flush(completion:) + 65

EventPipeline.swift - Line 34
closure #1 in EventPipeline.init(amplitude:) + 34

QueueTimer.swift - Line 38
closure #1 in QueueTimer.init(interval:once:queue:handler:) + 38
</details>

**Comment by crleona** [comment]
Thanks @slava-semeniuk-ek! This was caused by some concurrency issues that were largely resolved in 1.5.0+, but we missed one callback in IdentifyInterceptor, which I've fixed in https://github.com/amplitude/Amplitude-Swift/pull/176. I've also added some additional diagnostic logging which will help us catch similar issues in the future. Our write patterns are such that events in one of the removed files should have been either uploaded or re-written to another file, so we don't believe this has caused any data issues.

**Comment by crleona** [comment]
This should be released in 1.6.1

**Comment by slava-semeniuk-ek** [comment]
@crleona hey, hey, have you had a chance to check the additional diagnostic logging? It looks like these errors are still appearing

**Comment by slava-semeniuk-ek** [comment]
@crleona It seems it's still not fixed for 1.7.0. Could you please check the additional diagnostic logging? Let me know If you need any details from my side
